export const navItems = [
  {
    title: 'Switch Organization',
    icon: '/icons/nav-icon-4.svg',
    link: '#',
    id: 1,
  },
  {
    title: 'Dashboard',
    icon: '/icons/home.svg',
    link: '/dashboard',
    id: 2,
  },
  {
    title: 'Customers',
    header: true,
    link: '',
    id: 3,
  },
  {
    title: 'Users',
    icon: '/icons/nav-icon-4.svg',
    link: '/dashboard/users',
    id: 4,
  },
  {
    title: 'Guarantors',
    icon: '/icons/nav-icon-5.svg',
    link: '#',
    id: 5,
  },
  {
    title: 'Loan',
    icon: '/icons/nav-icon-6.svg',
    link: '#',
    id: 6,
  },
  {
    title: 'Decision Models',
    icon: '/icons/nav-icon-7.svg',
    link: '#',
    id: 7,
  },
  {
    title: 'Savings',
    icon: '/icons/nav-icon-8.svg',
    link: '#',
    id: 8,
  },
  {
    title: 'Loan Requests',
    icon: '/icons/nav-icon-9.svg',
    link: '#',
    id: 9,
  },
  {
    title: 'Whitelist',
    icon: '/icons/nav-icon-10.svg',
    link: '#',
    id: 10,
  },
  {
    title: 'Karma',
    icon: '/icons/nav-icon-11.svg',
    link: '#',
    id: 11,
  },
  {
    title: 'Businesses',
    header: true,
    link: '',
    id: 12,
  },
  {
    title: 'Organization',
    icon: '/icons/nav-icon-13.svg',
    link: '#',
    id: 13,
  },
  {
    title: 'Loan Products',
    icon: '/icons/nav-icon-14.svg',
    link: '#',
    id: 14,
  },
  {
    title: 'Savings Products',
    icon: '/icons/nav-icon-15.svg',
    link: '#',
    id: 15,
  },
  {
    title: 'Fees and Charges',
    icon: '/icons/nav-icon-16.svg',
    link: '#',
    id: 16,
  },
  {
    title: 'Transactions',
    icon: '/icons/nav-icon-17.svg',
    link: '#',
    id: 17,
  },
  {
    title: 'Services',
    icon: '/icons/nav-icon-18.svg',
    link: '#',
    id: 18,
  },
  {
    title: 'Service Account',
    icon: '/icons/nav-icon-19.svg',
    link: '#',
    id: 19,
  },
  {
    title: 'Settlements',
    icon: '/icons/nav-icon-20.svg',
    link: '#',
    id: 20,
  },
  {
    title: 'Reports',
    icon: '/icons/nav-icon-21.svg',
    link: '#',
    id: 21,
  },
  {
    title: 'Settings',
    header: true,
    link: '',
    id: 22,
  },
  {
    title: 'Preferences',
    icon: '/icons/nav-icon-23.svg',
    link: '#',
    id: 23,
  },
  {
    title: 'Fees and Pricing',
    icon: '/icons/nav-icon-24.svg',
    link: '#',
    id: 24,
  },
  {
    title: 'Audit Logs',
    icon: '/icons/nav-icon-25.svg',
    link: '#',
    id: 25,
  },
];

export const usersStats = [
  {
    title: 'Users',
    icon: '/icons/user-stat-icon-1.svg',
    count: '2,453',
  },
  {
    title: 'Active Users',
    icon: '/icons/user-stat-icon-2.svg',
    count: '2,453',
  },
  {
    title: 'Users with loans',
    icon: '/icons/user-stat-icon-3.svg',
    count: '12,453',
  },
  {
    title: 'Users with savings',
    icon: '/icons/user-stat-icon-4.svg',
    count: '102,453',
  },
];
